[2022-10-01 23:08:42,971] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-01T22:05:00+00:00 [queued]>
[2022-10-01 23:08:43,074] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-01T22:05:00+00:00 [queued]>
[2022-10-01 23:08:43,080] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 23:08:43,091] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-10-01 23:08:43,101] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 23:08:43,206] {taskinstance.py:1259} INFO - Executing <Task(DockerOperator): docker_command_sleep> on 2022-10-01 22:05:00+00:00
[2022-10-01 23:08:43,226] {standard_task_runner.py:52} INFO - Started process 374 to run task
[2022-10-01 23:08:43,279] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'docker_operator_demo', 'docker_command_sleep', 'scheduled__2022-10-01T22:05:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpke97mbx2', '--error-file', '/tmp/tmp9ylfq8_e']
[2022-10-01 23:08:43,282] {standard_task_runner.py:77} INFO - Job 5: Subtask docker_command_sleep
[2022-10-01 23:08:43,528] {logging_mixin.py:109} INFO - Running <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-01T22:05:00+00:00 [running]> on host 336e822c453c
[2022-10-01 23:08:43,780] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker_operator_demo
AIRFLOW_CTX_TASK_ID=docker_command_sleep
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T22:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-01T22:05:00+00:00
[2022-10-01 23:08:43,886] {docker.py:374} INFO - Pulling docker image alpine:latest
[2022-10-01 23:08:45,892] {docker.py:388} INFO - latest: Pulling from library/alpine
[2022-10-01 23:08:46,287] {docker.py:388} INFO - 9b18e9b68314: Pulling fs layer
[2022-10-01 23:08:46,768] {docker.py:388} INFO - 9b18e9b68314: Downloading
[2022-10-01 23:08:46,858] {docker.py:388} INFO - 9b18e9b68314: Verifying Checksum
[2022-10-01 23:08:46,866] {docker.py:388} INFO - 9b18e9b68314: Extracting
[2022-10-01 23:08:47,270] {docker.py:388} INFO - 9b18e9b68314: Pull complete
[2022-10-01 23:08:47,291] {docker.py:383} INFO - Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
[2022-10-01 23:08:47,297] {docker.py:383} INFO - Status: Downloaded newer image for alpine:latest
[2022-10-01 23:08:47,313] {docker.py:258} INFO - Starting docker container from image alpine:latest
[2022-10-01 23:08:47,383] {docker.py:269} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2022-10-01 23:08:47,985] {docker.py:320} INFO - hello
[2022-10-01 23:08:48,434] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=docker_operator_demo, task_id=docker_command_sleep, execution_date=20221001T220500, start_date=20221001T230842, end_date=20221001T230848
[2022-10-01 23:08:48,563] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-01 23:08:48,693] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
